# Generated by Django 5.2 on 2025-04-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_rating'),
        ('vehicle', '0003_alter_vehicle_daily_rate_alter_vehicle_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_license_image',
            field=models.ImageField(default=1, upload_to='drivers_licenses/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='vehicle.vehicle'),
            preserve_default=False,
        ),
    ]
