# Generated by Django 5.2 on 2025-04-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
