# Generated by Django 5.2 on 2025-04-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
        ('companylocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='administrative_level',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='department',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='service_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_location', to='companylocation.comapanylocation'),
        ),
    ]
