# Generated by Django 5.2 on 2025-04-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('total_seats', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_state', models.CharField(blank=True, max_length=50, null=True)),
                ('to_state', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('has_entourage_option', models.BooleanField(default=False)),
                ('has_security_option', models.BooleanField(default=False)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('fuel_efficiency', models.FloatField(blank=True, null=True)),
                ('has_gps_tracker', models.BooleanField(default=False)),
                ('tracker_id', models.CharField(blank=True, max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amenities', models.ManyToManyField(to='vehicle.amenity')),
                ('category', models.ManyToManyField(to='vehicle.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vehicle.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='vehicle_veh_vehicle_9a7388_idx')],
            },
        ),
    ]
