# Generated by Django 5.2 on 2025-04-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ManyToManyField(null=True, to='vehicle.vehicletype'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='amenities',
            field=models.ManyToManyField(null=True, to='vehicle.amenity'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.vehicle')),
            ],
        ),
    ]
