# Generated by Django 5.2 on 2025-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_amenity_alter_vehicle_options_remove_vehicle_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='amenities',
            field=models.ManyToManyField(to='vehicle.amenity'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.ManyToManyField(to='vehicle.vehicletype'),
        ),
    ]
