# Generated by Django 5.2 on 2025-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_amenity_icon_alter_amenity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='estimated_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='from_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='to_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
