# Generated by Django 5.2 on 2025-04-08 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('RT', 'Round Trip'), ('OW', 'One Way'), ('HR', 'Hourly Rental'), ('DR', 'Daily Rental')], max_length=2)),
                ('pickup_type', models.CharField(choices=[('HOME', 'Home Pickup'), ('PARK', 'Park Meeting')], max_length=10)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('people', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.DateTimeField()),
                ('luggage', models.PositiveIntegerField()),
                ('with_entourage', models.BooleanField(default=False)),
                ('with_security', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_dropoff_time', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_time', models.DateTimeField(blank=True, null=True)),
                ('booking_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('is_checked_in', models.BooleanField(default=False)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle')),
            ],
        ),
    ]
