# Generated by Django 5.2 on 2025-04-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_address',
            field=models.TextField(default=1, verbose_name='To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='origin_address',
            field=models.TextField(default=1, verbose_name='From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('OW', 'One Way'), ('RT', 'Round Trip'), ('HR', 'Hourly Rental'), ('DR', 'Daily Rental')], max_length=2),
        ),
    ]
