# Generated by Django 5.2 on 2025-04-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companylocation', '0001_initial'),
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatcher',
            name='dispatch_region',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='shift',
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='service_region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_location', to='companylocation.comapanylocation'),
        ),
    ]
